/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model;


import com.magicghostvu.model.tables.Adminroles;
import com.magicghostvu.model.tables.Game;
import com.magicghostvu.model.tables.Gametag;
import com.magicghostvu.model.tables.Gameversion;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMINROLES_DOMAINNAME_ROLE_IDX = Internal.createIndex(DSL.name("AdminRoles_domainName_role_idx"), Adminroles.ADMINROLES, new OrderField[] { Adminroles.ADMINROLES.DOMAINNAME, Adminroles.ADMINROLES.ROLE }, false);
    public static final Index ADMINROLES_DOMAINNAME_ROLE_KEY = Internal.createIndex(DSL.name("AdminRoles_domainName_role_key"), Adminroles.ADMINROLES, new OrderField[] { Adminroles.ADMINROLES.DOMAINNAME, Adminroles.ADMINROLES.ROLE }, true);
    public static final Index GAME_CREATETIME_ID_AUTHORID_LASTUPDATETIME_PARENTGAMEID_IDX = Internal.createIndex(DSL.name("Game_createTime_id_authorId_lastUpdateTime_parentGameId_idx"), Game.GAME, new OrderField[] { Game.GAME.CREATETIME, Game.GAME.ID, Game.GAME.AUTHORID, Game.GAME.LASTUPDATETIME, Game.GAME.PARENTGAMEID }, false);
    public static final Index GAMETAG_GAMEID_TAG_IDX = Internal.createIndex(DSL.name("GameTag_gameId_tag_idx"), Gametag.GAMETAG, new OrderField[] { Gametag.GAMETAG.GAMEID, Gametag.GAMETAG.TAG }, false);
    public static final Index GAMETAG_GAMEID_TAG_KEY = Internal.createIndex(DSL.name("GameTag_gameId_tag_key"), Gametag.GAMETAG, new OrderField[] { Gametag.GAMETAG.GAMEID, Gametag.GAMETAG.TAG }, true);
    public static final Index GAMEVERSION_GAMEID_ID_KEY = Internal.createIndex(DSL.name("GameVersion_gameId_id_key"), Gameversion.GAMEVERSION, new OrderField[] { Gameversion.GAMEVERSION.GAMEID, Gameversion.GAMEVERSION.ID }, true);
    public static final Index GAMEVERSION_GAMEID_STATUS_CREATEDTIME_UNIQUE_IDX = Internal.createIndex(DSL.name("GameVersion_gameId_status_createdTime_unique_idx"), Gameversion.GAMEVERSION, new OrderField[] { Gameversion.GAMEVERSION.GAMEID, Gameversion.GAMEVERSION.STATUS, Gameversion.GAMEVERSION.CREATEDTIME, Gameversion.GAMEVERSION.UNIQUE }, false);
}
