/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model;


import com.magicghostvu.model.tables.Adminroles;
import com.magicghostvu.model.tables.Adminuser;
import com.magicghostvu.model.tables.Game;
import com.magicghostvu.model.tables.Gametag;
import com.magicghostvu.model.tables.Gameversion;
import com.magicghostvu.model.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.AdminRoles</code>.
     */
    public final Adminroles ADMINROLES = Adminroles.ADMINROLES;

    /**
     * The table <code>public.AdminUser</code>.
     */
    public final Adminuser ADMINUSER = Adminuser.ADMINUSER;

    /**
     * The table <code>public.Game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>public.GameTag</code>.
     */
    public final Gametag GAMETAG = Gametag.GAMETAG;

    /**
     * The table <code>public.GameVersion</code>.
     */
    public final Gameversion GAMEVERSION = Gameversion.GAMEVERSION;

    /**
     * The table <code>public.User</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.GAME_ID_SEQ,
            Sequences.GAMEVERSION_UNIQUE_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Adminroles.ADMINROLES,
            Adminuser.ADMINUSER,
            Game.GAME,
            Gametag.GAMETAG,
            Gameversion.GAMEVERSION,
            User.USER
        );
    }
}
