/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.Game_id_seq</code>
     */
    public static final Sequence<Long> GAME_ID_SEQ = Internal.createSequence("Game_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.GameVersion_unique_seq</code>
     */
    public static final Sequence<Long> GAMEVERSION_UNIQUE_SEQ = Internal.createSequence("GameVersion_unique_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
