/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model;


import com.magicghostvu.model.tables.Adminroles;
import com.magicghostvu.model.tables.Adminuser;
import com.magicghostvu.model.tables.Game;
import com.magicghostvu.model.tables.Gametag;
import com.magicghostvu.model.tables.Gameversion;
import com.magicghostvu.model.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.AdminRoles</code>.
     */
    public static final Adminroles ADMINROLES = Adminroles.ADMINROLES;

    /**
     * The table <code>public.AdminUser</code>.
     */
    public static final Adminuser ADMINUSER = Adminuser.ADMINUSER;

    /**
     * The table <code>public.Game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>public.GameTag</code>.
     */
    public static final Gametag GAMETAG = Gametag.GAMETAG;

    /**
     * The table <code>public.GameVersion</code>.
     */
    public static final Gameversion GAMEVERSION = Gameversion.GAMEVERSION;

    /**
     * The table <code>public.User</code>.
     */
    public static final User USER = User.USER;
}
