/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model.tables.pojos;


import com.magicghostvu.model.enums.Gameversionstatus;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gameversion implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final Long gameid;
    private final Gameversionstatus status;
    private final Long createdtime;
    private final Long unique;

    public Gameversion(Gameversion value) {
        this.id = value.id;
        this.gameid = value.gameid;
        this.status = value.status;
        this.createdtime = value.createdtime;
        this.unique = value.unique;
    }

    public Gameversion(
        Integer id,
        Long gameid,
        Gameversionstatus status,
        Long createdtime,
        Long unique
    ) {
        this.id = id;
        this.gameid = gameid;
        this.status = status;
        this.createdtime = createdtime;
        this.unique = unique;
    }

    /**
     * Getter for <code>public.GameVersion.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.GameVersion.gameId</code>.
     */
    public Long getGameid() {
        return this.gameid;
    }

    /**
     * Getter for <code>public.GameVersion.status</code>.
     */
    public Gameversionstatus getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>public.GameVersion.createdTime</code>.
     */
    public Long getCreatedtime() {
        return this.createdtime;
    }

    /**
     * Getter for <code>public.GameVersion.unique</code>.
     */
    public Long getUnique() {
        return this.unique;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Gameversion other = (Gameversion) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gameid == null) {
            if (other.gameid != null)
                return false;
        }
        else if (!this.gameid.equals(other.gameid))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdtime == null) {
            if (other.createdtime != null)
                return false;
        }
        else if (!this.createdtime.equals(other.createdtime))
            return false;
        if (this.unique == null) {
            if (other.unique != null)
                return false;
        }
        else if (!this.unique.equals(other.unique))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gameid == null) ? 0 : this.gameid.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdtime == null) ? 0 : this.createdtime.hashCode());
        result = prime * result + ((this.unique == null) ? 0 : this.unique.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Gameversion (");

        sb.append(id);
        sb.append(", ").append(gameid);
        sb.append(", ").append(status);
        sb.append(", ").append(createdtime);
        sb.append(", ").append(unique);

        sb.append(")");
        return sb.toString();
    }
}
