/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gametag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long gameid;
    private final String tag;

    public Gametag(Gametag value) {
        this.gameid = value.gameid;
        this.tag = value.tag;
    }

    public Gametag(
        Long gameid,
        String tag
    ) {
        this.gameid = gameid;
        this.tag = tag;
    }

    /**
     * Getter for <code>public.GameTag.gameId</code>.
     */
    public Long getGameid() {
        return this.gameid;
    }

    /**
     * Getter for <code>public.GameTag.tag</code>.
     */
    public String getTag() {
        return this.tag;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Gametag other = (Gametag) obj;
        if (this.gameid == null) {
            if (other.gameid != null)
                return false;
        }
        else if (!this.gameid.equals(other.gameid))
            return false;
        if (this.tag == null) {
            if (other.tag != null)
                return false;
        }
        else if (!this.tag.equals(other.tag))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.gameid == null) ? 0 : this.gameid.hashCode());
        result = prime * result + ((this.tag == null) ? 0 : this.tag.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Gametag (");

        sb.append(gameid);
        sb.append(", ").append(tag);

        sb.append(")");
        return sb.toString();
    }
}
