/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model.tables;


import com.magicghostvu.model.Keys;
import com.magicghostvu.model.Public;
import com.magicghostvu.model.tables.records.AdminuserRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function1;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adminuser extends TableImpl<AdminuserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.AdminUser</code>
     */
    public static final Adminuser ADMINUSER = new Adminuser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdminuserRecord> getRecordType() {
        return AdminuserRecord.class;
    }

    /**
     * The column <code>public.AdminUser.domainName</code>.
     */
    public final TableField<AdminuserRecord, String> DOMAINNAME = createField(DSL.name("domainName"), SQLDataType.CLOB.nullable(false), this, "");

    private Adminuser(Name alias, Table<AdminuserRecord> aliased) {
        this(alias, aliased, null);
    }

    private Adminuser(Name alias, Table<AdminuserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.AdminUser</code> table reference
     */
    public Adminuser(String alias) {
        this(DSL.name(alias), ADMINUSER);
    }

    /**
     * Create an aliased <code>public.AdminUser</code> table reference
     */
    public Adminuser(Name alias) {
        this(alias, ADMINUSER);
    }

    /**
     * Create a <code>public.AdminUser</code> table reference
     */
    public Adminuser() {
        this(DSL.name("AdminUser"), null);
    }

    public <O extends Record> Adminuser(Table<O> child, ForeignKey<O, AdminuserRecord> key) {
        super(child, key, ADMINUSER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AdminuserRecord> getPrimaryKey() {
        return Keys.ADMINUSER_PKEY;
    }

    @Override
    public Adminuser as(String alias) {
        return new Adminuser(DSL.name(alias), this);
    }

    @Override
    public Adminuser as(Name alias) {
        return new Adminuser(alias, this);
    }

    @Override
    public Adminuser as(Table<?> alias) {
        return new Adminuser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Adminuser rename(String name) {
        return new Adminuser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adminuser rename(Name name) {
        return new Adminuser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adminuser rename(Table<?> name) {
        return new Adminuser(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
