/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model.enums;


import com.magicghostvu.model.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Gametype implements EnumType {

    SingleGame("SingleGame"),

    SubGame("SubGame"),

    HubGame("HubGame");

    private final String literal;

    private Gametype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "GameType";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static Gametype lookupLiteral(String literal) {
        return EnumType.lookupLiteral(Gametype.class, literal);
    }
}
