/*
 * This file is generated by jOOQ.
 */
package com.magicghostvu.model.tables.records;


import com.magicghostvu.model.tables.Gametag;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GametagRecord extends TableRecordImpl<GametagRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.GameTag.gameId</code>.
     */
    public GametagRecord setGameid(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.GameTag.gameId</code>.
     */
    public Long getGameid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.GameTag.tag</code>.
     */
    public GametagRecord setTag(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.GameTag.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Gametag.GAMETAG.GAMEID;
    }

    @Override
    public Field<String> field2() {
        return Gametag.GAMETAG.TAG;
    }

    @Override
    public Long component1() {
        return getGameid();
    }

    @Override
    public String component2() {
        return getTag();
    }

    @Override
    public Long value1() {
        return getGameid();
    }

    @Override
    public String value2() {
        return getTag();
    }

    @Override
    public GametagRecord value1(Long value) {
        setGameid(value);
        return this;
    }

    @Override
    public GametagRecord value2(String value) {
        setTag(value);
        return this;
    }

    @Override
    public GametagRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GametagRecord
     */
    public GametagRecord() {
        super(Gametag.GAMETAG);
    }

    /**
     * Create a detached, initialised GametagRecord
     */
    public GametagRecord(Long gameid, String tag) {
        super(Gametag.GAMETAG);

        setGameid(gameid);
        setTag(tag);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GametagRecord
     */
    public GametagRecord(com.magicghostvu.model.tables.pojos.Gametag value) {
        super(Gametag.GAMETAG);

        if (value != null) {
            setGameid(value.getGameid());
            setTag(value.getTag());
            resetChangedOnNotNull();
        }
    }
}
